[program:gmail-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /www/wwwroot/your-domain.com/worker.php
autostart=true
autorestart=true
user=www
numprocs=2
redirect_stderr=true
stdout_logfile=/www/wwwroot/your-domain.com/storage/logs/worker.log
stopwaitsecs=3600
